import type { Config } from "tailwindcss"

const config = {
  darkMode: "class",
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#00000b",
          container: "#1a1a2e",
          fixed: "#e2e0fc",
          "fixed-dim": "#c6c4df",
          foreground: "#ffffff",
          "on-primary": "#ffffff",
          "on-primary-container": "#83829b",
          "on-primary-fixed": "#1a1a2e",
          "on-primary-fixed-variant": "#45455b",
        },
        secondary: {
          DEFAULT: "#535d7e",
          container: "#ced9ff",
          "fixed": "#dae1ff",
          "fixed-dim": "#bbc5eb",
          foreground: "#ffffff",
          "on-secondary": "#ffffff",
          "on-secondary-container": "#545e7f",
          "on-secondary-fixed": "#0f1a37",
          "on-secondary-fixed-variant": "#3b4665",
        },
        tertiary: {
          DEFAULT: "#000103",
          container: "#001e33",
          fixed: "#cee5ff",
          "fixed-dim": "#9acbfb",
          foreground: "#ffffff",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#5789b5",
          "on-tertiary-fixed": "#001d32",
          "on-tertiary-fixed-variant": "#0b4a73",
        },
        surface: {
          DEFAULT: "#fcf8fa",
          tint: "#5d5c74",
          bright: "#fcf8fa",
          dim: "#ddd9db",
          variant: "#e5e1e3",
          "container-low": "#f6f2f4",
          "container": "#f1edef",
          "container-high": "#ebe7e9",
          "container-highest": "#e5e1e3",
          "container-lowest": "#ffffff",
          on: "#1c1b1d",
          "on-surface": "#1c1b1d",
          "on-surface-variant": "#47464c",
          "on-background": "#1c1b1d",
        },
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
          on: "#ffffff",
          "on-error-container": "#93000a",
        },
        outline: {
          DEFAULT: "#78767d",
          variant: "#c8c5cd",
        },
        accent: {
          DEFAULT: "#3282b8",
          hover: "#2b71a1",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.25rem",
        sm: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "24px",
        "section-padding": "64px",
        "stack-md": "16px",
        "container-max": "1280px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-sm": "8px",
      },
      fontFamily: {
        h1: ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        h4: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h4: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config